[project]
name = "alg-painter"
version = "1.0.0"
description = "ALG-painter is a tool for interacting with Ancestral Linkage Groups. This data can be used for extracting, painting and plotting of ALGs from BUSCO full tables."
readme = "README.md"
authors = [
    { name = "DLBPointon", email = "damonlbp@hotmail.co.uk" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.0",
    "polars>=1.42.1",
    "requests>=2.34.2",
    "typer>=0.26.8",
]

[tool.ruff.lint.pycodestyle]
max-line-length = 80

[project.scripts]
alg = "alg_painter.cli:app"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[tool.setuptools.package-data]
alg_painter = ["assets/**/*", "fonts/**/*"]
