#!/usr/bin/env python3
"""
plotter_v1.py — Python conversion of plot_buscopainter.R

CONVERSION WAS AUTOMATICALLY GENERATED BY CLAUDE OPUS 4.6
AND TESTED AGAINST KNOWN OUTPUT

Original R script by  : Charlotte Wright
Original Repo       : https://github.com/charlottewright/lep_busco_painter/

Converted by        : AI assistant
Date of conversion  : 2026-04-14

Modified by         : Damon-Lee B Pointon
Modified on         : 2026-04-14

Description:
    This script generates a plot showing locations of putative
    merian elements (or species-level orthologs) in a genomic assembly.
    It is port of the R/ggplot2 version to Python/matplotlib.
"""

import argparse
import logging
from pathlib import Path

import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import pandas as pd

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Merian element ordering (shared across multiple functions)
# ---------------------------------------------------------------------------
MERIAN_ORDER = [
    "MZ",
    *[f"M{i}" for i in range(1, 32)],
    "self",
]

# ---------------------------------------------------------------------------
# Colour helpers
# ---------------------------------------------------------------------------


def hue_palette(n: int) -> list[str]:
    """
    Replicate ggplot2's ``hue_pal()`` which generates *n* evenly-spaced
    colours around the HCL colour wheel (approximated here with HSV).
    """
    colours = []
    for i in range(n):
        hue = (i / n + 0.025) % 1.0  # slight offset matches ggplot2
        colours.append(mcolors.hsv_to_rgb((hue, 0.65, 0.95)))
    return colours


def set_merian_colour_mapping(location_set: pd.DataFrame) -> dict:
    """
    Build a mapping of Merian element → colour for elements that are
    actually present in the data.  Mirrors R's ``set_merian_colour_mapping``.
    """
    colour_palette = hue_palette(32)
    colour_palette.append("grey")  # colour for "self"

    status_merians = location_set["status"].unique().tolist()
    mapping: dict = {}
    for merian, colour in zip(MERIAN_ORDER, colour_palette):
        if merian in status_merians:
            mapping[merian] = colour
    return mapping


# ---------------------------------------------------------------------------
# Data loading & filtering
# ---------------------------------------------------------------------------


def prepare_data(location_file: Path) -> pd.DataFrame:
    """Load a locations TSV and compute chromosome lengths from max position."""
    locations = pd.read_csv(location_file, sep="\t")

    # Remove rows where query_chr or assigned_chr contain ":"
    locations = locations[~locations["query_chr"].str.contains(":", na=False)]
    locations = locations[
        ~locations["assigned_chr"].str.contains(":", na=False)
    ]

    # Compute length per query chromosome as max position
    locations["length"] = locations.groupby("query_chr")["position"].transform(
        "max"
    )
    locations["start"] = 0

    return locations


def prepare_data_with_index(
    location_file: Path, index_file: Path
) -> pd.DataFrame:
    """Load locations TSV and merge with a genome index (.fai) for lengths."""
    locations = pd.read_csv(location_file, sep="\t")
    contig_lengths = pd.read_csv(
        index_file,
        sep="\t",
        header=None,
        names=["Seq", "length", "offset", "linebases", "linewidth"],
    )

    # Remove rows where query_chr or assigned_chr contain ":"
    locations = locations[~locations["query_chr"].str.contains(":", na=False)]
    locations = locations[
        ~locations["assigned_chr"].str.contains(":", na=False)
    ]

    # Merge to get actual contig lengths
    locations = locations.merge(
        contig_lengths[["Seq", "length"]],
        left_on="query_chr",
        right_on="Seq",
        how="left",
    )
    locations.drop(columns=["Seq"], inplace=True, errors="ignore")
    locations["start"] = 0

    return locations


def filter_buscos(locations: pd.DataFrame, minimum: int = 3) -> pd.DataFrame:
    """Keep only chromosomes with at least *minimum* BUSCOs."""
    filtered_locations = locations.copy()
    filtered_locations["n_busco"] = filtered_locations.groupby("query_chr")[
        "query_chr"
    ].transform("count")
    return filtered_locations[filtered_locations["n_busco"] >= minimum]


# ---------------------------------------------------------------------------
# Shared plotting helpers
# ---------------------------------------------------------------------------


def _chromosome_order(df: pd.DataFrame) -> list[str]:
    """Return chromosomes sorted by length descending (unique)."""
    chr_len = df[["query_chr", "length"]].drop_duplicates()
    chr_len = chr_len.sort_values("length", ascending=False)
    return chr_len["query_chr"].tolist()


def _apply_busco_paint_theme(ax: plt.Axes) -> None:
    """Apply the ``busco_paint_theme`` styling to an axes."""
    ax.set_facecolor("white")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_visible(False)
    ax.tick_params(left=False, labelleft=True)
    ax.xaxis.set_tick_params(labelsize=11)


def _draw_chromosome_row(
    ax: plt.Axes,
    y: float,
    start: float,
    length: float,
    busco_positions,
    busco_colours,
    bar_width: float,
    bar_height: int,
):
    """
    Draw one chromosome row: a white backbone + coloured BUSCO ticks.
    """
    # Backbone rectangle
    rect = mpatches.FancyBboxPatch(
        (start, y),
        length,
        bar_height,
        boxstyle="square,pad=0",
        facecolor="white",
        edgecolor="black",
        linewidth=0.5,
    )
    ax.add_patch(rect)

    # BUSCO markers
    for pos, col in zip(busco_positions, busco_colours):
        busco_rect = mpatches.FancyBboxPatch(
            (pos - bar_width, y),
            bar_width * 2,
            bar_height,
            boxstyle="square,pad=0",
            facecolor=col,
            edgecolor="none",
        )
        ax.add_patch(busco_rect)


# ---------------------------------------------------------------------------
# Core rendering function
# ---------------------------------------------------------------------------


def _render_chromosome_plot(
    spp_df: pd.DataFrame,
    colour_map: dict,
    colour_column: str,
    chr_order: list[str],
    legend_title: str,
    title: str,
    karyotype: str,
    bar_width: float,
    bar_height: int,
    legend_order: list[str] | None = None,
) -> plt.Figure:
    """
    Core rendering function for all chromosome paint plots.

    Parameters
    ----------
    spp_df          : DataFrame with at least query_chr, position, length,
                      and the column named by ``colour_column``.
    colour_map      : {value: colour} mapping for the colour_column.
    colour_column   : Column name to look up colours from
                      (``"status"`` or ``"assigned_chr"``).
    chr_order       : Pre-sorted list of chromosomes to plot
                      (already filtered if needed).
    legend_title    : Title for the legend
                      (``"Merian element"`` or ``"Query chromosome"``).
    title           : Plot title (species name, rendered italic).
    karyotype       : Subtitle string (number of contigs).
    bar_width       : Half-width of each BUSCO marker in bp.
    bar_height      : Height of each chromosome bar.
    legend_order    : If provided, only include these keys (in order) in the
                      legend, filtered to values present in the data.
                      If ``None``, use all ``colour_map`` keys.
    """
    spp_df = spp_df.copy()
    sub_title = f"n contigs = {karyotype}"

    n_chroms = len(chr_order)
    row_height = bar_height + 4
    fig_height = max(8, n_chroms * 0.55)
    fig, ax = plt.subplots(figsize=(15 / 2.54 * 2, fig_height))

    for idx, chrom in enumerate(chr_order):
        chrom_data = spp_df[spp_df["query_chr"] == chrom]
        y = idx * row_height
        length = chrom_data["length"].iloc[0] if not chrom_data.empty else 0

        positions = chrom_data["position"].values
        colours = [
            colour_map.get(val, "lightgrey")
            for val in chrom_data[colour_column]
        ]
        _draw_chromosome_row(
            ax,
            y,
            0,
            length,
            positions,
            colours,
            bar_width=bar_width,
            bar_height=bar_height,
        )

        ax.text(
            -0.01 * spp_df["length"].max(),
            y + bar_height / 2,
            chrom,
            ha="right",
            va="center",
            fontsize=9,
        )

    # Axes formatting
    ax.set_xlim(-0.15 * spp_df["length"].max(), spp_df["length"].max() * 1.05)
    ax.set_ylim(-row_height, n_chroms * row_height)
    ax.set_xlabel("Position (Mb)", fontsize=12)
    ax.xaxis.set_major_formatter(
        plt.FuncFormatter(lambda x, _: f"{x / 1e6:.0f}")
    )
    ax.set_yticks([])

    ax.set_title(f"$\\it{{{title}}}$\n{sub_title}", fontsize=14)

    # Legend
    if legend_order is not None:
        present = set(spp_df[colour_column].unique())
        legend_keys = [k for k in legend_order if k in present]
    else:
        legend_keys = list(colour_map.keys())

    legend_handles = [
        mpatches.Patch(facecolor=colour_map.get(k, "lightgrey"), label=k)
        for k in legend_keys
    ]
    ax.legend(
        handles=legend_handles,
        title=legend_title,
        loc="center left",
        bbox_to_anchor=(1.01, 0.5),
        frameon=False,
        fontsize=9,
    )

    _apply_busco_paint_theme(ax)
    fig.tight_layout()
    return fig


# ---------------------------------------------------------------------------
# Four public plot functions (thin wrappers around _render_chromosome_plot)
# ---------------------------------------------------------------------------


def paint_merians_differences_only(
    spp_df: pd.DataFrame,
    subset_merians: dict,
    num_col: int,
    title: str,
    karyotype: str,
    bar_width: float,
    bar_height: int,
) -> plt.Figure:
    """Plot only BUSCOs that have moved — coloured by Merian element."""
    chr_order = _chromosome_order(spp_df)
    return _render_chromosome_plot(
        spp_df,
        subset_merians,
        "status",
        chr_order,
        "Merian element",
        title,
        karyotype,
        bar_width,
        bar_height,
    )


def paint_species_differences_only(
    spp_df: pd.DataFrame,
    num_col: int,
    title: str,
    karyotype: str,
    bar_width: float,
    bar_height: int,
) -> plt.Figure:
    """Plot only BUSCOs that have moved — coloured by species/query chromosome."""
    chr_order = _chromosome_order(spp_df)
    chr_order = [c for c in chr_order if c != "self"]

    legend_levels = spp_df["status"].unique().tolist()
    legend_levels = [level for level in legend_levels if level != "self"]
    legend_levels = ["self"] + legend_levels

    col_palette_raw = hue_palette(len(legend_levels))
    col_palette_raw[0] = "grey"  # "self" → grey
    col_palette = dict(zip(legend_levels, col_palette_raw))

    return _render_chromosome_plot(
        spp_df,
        col_palette,
        "status",
        chr_order,
        "Query chromosome",
        title,
        karyotype,
        bar_width,
        bar_height,
    )


def paint_merians_all(
    spp_df: pd.DataFrame,
    num_col: int,
    title: str,
    karyotype: str,
    bar_width: float,
    bar_height: int,
) -> plt.Figure:
    """Plot ALL BUSCOs — coloured by Merian element (assigned_chr)."""
    colour_palette_raw = hue_palette(
        32
    )  # THIS COULD BE UPDATED FOR ALG UNIT COUNT
    colour_palette_raw.append("grey")  # for "self"
    colour_palette = dict(zip(MERIAN_ORDER, colour_palette_raw))
    chr_order = _chromosome_order(spp_df)

    return _render_chromosome_plot(
        spp_df,
        colour_palette,
        "assigned_chr",
        chr_order,
        "Merian element",
        title,
        karyotype,
        bar_width,
        bar_height,
        legend_order=MERIAN_ORDER,
    )


def paint_species_all(
    spp_df: pd.DataFrame,
    num_col: int,
    title: str,
    karyotype: str,
    bar_width: float,
    bar_height: int,
) -> plt.Figure:
    """Plot ALL BUSCOs — coloured by species/assigned chromosome."""
    chr_order = _chromosome_order(spp_df)
    chr_order = [c for c in chr_order if c != "self"]

    legend_levels = spp_df["assigned_chr"].unique().tolist()
    col_palette = dict(zip(legend_levels, hue_palette(len(legend_levels))))

    return _render_chromosome_plot(
        spp_df,
        col_palette,
        "assigned_chr",
        chr_order,
        "Query chromosome",
        title,
        karyotype,
        bar_width,
        bar_height,
    )


# ---------------------------------------------------------------------------
# Save helper
# ---------------------------------------------------------------------------


def save_plot(fig: plt.Figure, base_path: str) -> None:
    """Save figure as both PNG and PDF (mirrors R script's ggsave calls)."""
    for ext in ("png", "pdf"):
        out = f"{base_path}_buscopainter.{ext}"
        fig.savefig(out, dpi=300, bbox_inches="tight")
        logger.info("[Plotter V1] Saved: %s", out)
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def plotter_v1_main(args: argparse.Namespace) -> None:
    """
    Main orchestration — mirrors the bottom half of the R script.
    Can be called from the CLI or imported and called with an args namespace.
    """
    if args.index is None:
        location_set = prepare_data(args.file)
    else:
        location_set = prepare_data_with_index(args.file, args.index)

    locations_filt = filter_buscos(location_set, args.minimum)

    # ---- Reporting --------------------------------------------------------
    total_contigs = location_set["query_chr"].nunique()
    num_contigs = locations_filt["query_chr"].nunique()
    num_removed = total_contigs - num_contigs

    logger.info(
        f"[Plotter V1] Number of contigs before filtering by number of BUSCOs: {total_contigs}"
    )
    logger.info(
        f"[Plotter V1] Number of contigs removed by filtering : {num_removed}"
    )
    logger.info(
        f"[Plotter V1] Number of contigs post-filtering: {num_contigs}"
    )

    num_contigs_str = str(num_contigs)
    bw = args.bar_width
    bh = args.bar_height

    # ---- Select plot function based on flags ------------------------------
    if args.merians:
        subset_merians: dict[str, str] = set_merian_colour_mapping(
            locations_filt
        )

        if not args.differences:
            fig = paint_merians_all(
                locations_filt,
                1,
                args.prefix,
                num_contigs_str,
                bar_width=bw,
                bar_height=bh,
            )
        else:
            num_col = (
                1 if len(locations_filt["query_chr"].unique()) < 100 else 3
            )
            fig = paint_merians_differences_only(
                locations_filt,
                subset_merians,
                num_col,
                args.prefix,
                num_contigs_str,
                bar_width=bw,
                bar_height=bh,
            )
    else:
        if not args.differences:
            fig = paint_species_all(
                locations_filt,
                1,
                args.prefix,
                num_contigs_str,
                bar_width=bw,
                bar_height=bh,
            )
        else:
            fig = paint_species_differences_only(
                locations_filt,
                1,
                args.prefix,
                num_contigs_str,
                bar_width=bw,
                bar_height=bh,
            )

    # ---- Save outputs -----------------------------------------------------
    logger.info(f"[Plotter V1] Saving plot to: {str(args.file)}")
    save_plot(fig, str(args.file))
